# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:15"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
    assignees:
      - "YashTotale"
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
      time: "07:15"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
    assignees:
      - "YashTotale"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:15"
      timezone: "America/Los_Angeles"
    assignees:
      - "YashTotale"
