name: Build Wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: npm ci

      - name: Build Wiki
        run: npm run buildwiki

      - name: Push Wiki
        run: |
          cd wiki
          git add .
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git commit --allow-empty -m "Changes"
          git push https://YashTotale:${{ secrets.GH_PAT }}@github.com/YashTotale/react-hash-scroll.wiki.git
          cd ..
          rm -rf wiki
