name: Build Wiki

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: npm ci

      - name: Configure Git
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          name: "Yash Totale"
          email: "totaleyash@gmail.com"
          actor: "YashTotale"
          token: "${{ secrets.GH_PAT }}"

      - name: Build Wiki
        run: npm run buildwiki
